#ifndef __GM6721X_SOC_H__
#define __GM6721X_SOC_H__
/* Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib) */
#define CONFIG_ARM 1

/********************************************/
/* General Architecture Options */
/********************************************/

/********************************************/
/* Interrupt Configuration */
/********************************************/
#define CONFIG_GEN_ISR_TABLES 1
#define CONFIG_GEN_IRQ_VECTOR_TABLE 1
#define CONFIG_GEN_SW_ISR_TABLE 1
#define CONFIG_GEN_IRQ_START_VECTOR 0
#define CONFIG_ARCH_HAS_THREAD_ABORT 1
#define CONFIG_CPU_HAS_FPU 1
#define CONFIG_CPU_HAS_MPU 1



/********************************************/
/* ARM Options */
/********************************************/
#define CONFIG_CPU_CORTEX 1
#define CONFIG_CPU_CORTEX_M 1
#define CONFIG_CPU_HAS_SYSTICK 1

/********************************************/
/* Architecture Floating Point Options */
/********************************************/
#define CONFIG_FP_HARDABI 1
#define CONFIG_CPU_CORTEX_M4 1
#define CONFIG_ISA_THUMB2 1
#define CONFIG_CPU_CORTEX_M_HAS_BASEPRI 1
#define CONFIG_CPU_CORTEX_M_HAS_VTOR 1
#define CONFIG_CPU_CORTEX_M_HAS_PROGRAMMABLE_FAULT_PRIOS 1
#define CONFIG_ARMV7_M_ARMV8_M_MAINLINE 1
#define CONFIG_ARMV7_M_ARMV8_M_FP 1

/********************************************/
/* ARM Cortex-M options */
/********************************************/
#define CONFIG_LDREX_STREX_AVAILABLE 1
#define CONFIG_DATA_ENDIANNESS_LITTLE 1
#define CONFIG_STACK_ALIGN_DOUBLE_WORD 1
#define CONFIG_FAULT_DUMP 2


/********************************************/
/* Floating Point Options */
/********************************************/
#define CONFIG_FLOAT 1
#define CONFIG_FP_SHARING 1

/********************************************/
/* SoC Serial Configuration */
/********************************************/
#define CONFIG_ARCH "arm"
#define CONFIG_SOC_FAMILY "gree_gm"
#define CONFIG_SOC_SERIES "gm6721x"

/********************************************/
#endif