/* Generated automatically by the program `genattr-common'
   from the machine description file `md'.  */

#ifndef GCC_INSN_ATTR_COMMON_H
#define GCC_INSN_ATTR_COMMON_H

enum attr_type {TYPE_UNKNOWN, TYPE_COMPLEX, TYPE_CONTROL, TYPE_ALU, TYPE_COND_ALU, TYPE_ST, TYPE_LD, TYPE_STWM, TYPE_LDWM, TYPE_PUSH, TYPE_POP, TYPE_MUL, TYPE_DIV, TYPE_CUSTOM, TYPE_ADD, TYPE_SUB, TYPE_MOV, TYPE_AND, TYPE_OR, TYPE_XOR, TYPE_NEG, TYPE_NOT, TYPE_SLL, TYPE_SRL, TYPE_SRA, TYPE_ROL, TYPE_ROR, TYPE_NOP};
#define INSN_SCHEDULING
#define DELAY_SLOTS 0

#endif /* GCC_INSN_ATTR_COMMON_H */
