#
# DESCRIPTION: A user-kindly GDB configuration script file, for the IOT uGelis OS on ARM architecture
#
# REVISION: 1.0.0  (04/11/2017)
#
# CONTRIBUTORS: wizephen.wang
#


#golbal para
set	$sdram_d0_16m_4b       = 1
set $SDRAM_MEM_START_ADDR = 0xC0000000

set       $SDRAM_DQ_Mode          = 0x1 	
set       $SDRAM_Cas_Latency      = 0x3
set       $SDRAM_Ras_ActTime      =	0x3
set       $SDRAM_Ras_RefCyc       =	0x5
set       $SDRAM_CtoC_dly         =	0x0
set       $SDRAM_RtoR_dly         =	0x1
set       $SDRAM_RtoC_dly         =	0x1
set       $SDRAM_Ras_PreTime      =	0x1
set       $SDRAM_TurnAround_Mode  =	0x0
set       $SDRAM_OE_Post_En       = 0x0
set       $SDRAM_OE_Pre_En        = 0x0
set       $SDRAM_Burst_Length     = ($SDRAM_DQ_Mode+0x2)
set       $SDRAM_Dimm1_En         = 0x0
set       $SDRAM_Dimm_Bank_Map    = 0x1
set       $SDRAM_Dimm_Map         =	0x4
set       $SDRAM_Conti_Setting    = 0x0


set       $SDRAM_CPU_Req_Prio     = 	0x1
set       $SDRAM_Main_Arbt_Mode    =	0x0
set       $SDRAM_SubA_Arbt_Mode   = 	0x0
set       $SDRAM_SubB_Arbt_Mode    =	0x0

#--------FOR LOAD  PARAMTER
set       $SDRAM_Row_Map           =	0x4

set       $SDRAM_Row1_Base        = 	0x01000000
set       $SDRAM_WRDLock_Timer_En  =	0x0
set       $SDRAM_WRDLock_Exit_En   =	0x0

#set      $SDRAM_Refresh_Time     = 	0x0d
set       $SDRAM_Refresh_Time     = 	0x05
set       $SDRAM_Clk_Tree_Dly      =	0x0
set       $SDRAM_Interleave       = 	0x0
set       $SDRAM_Read_Dly         = 	0x0
set 	  $SDRAM_CTRL_REG		  =	0x40039280

define debug_sdram
  set $temp1 = 0
	set $temp2 = 0
	set $temp1 = *((unsigned int*)$SDRAM_CTRL_REG)
	set $temp2 = *((unsigned int*)$SDRAM_CTRL_REG+0x4)
	
	printf "SDRAM_CTRL_REG   is %x\n", $temp1
	printf "SDRAM_CTRL_REG+4 is %x\n", $temp2
end

#SDRAM_Wait_Idle
define SDRAM_Wait_Idle
	printf "SDRAM_Wait_Idle-0\n"
	set $flag = 0x1
	printf "SDRAM_Wait_Idle-1\n"
	set $temp_mem = 0
	printf "SDRAM_Wait_Idle-2\n"

	while $flag
		printf "SDRAM_Wait_Idle-3\n"
		set $temp_mem = *((unsigned int*)$SDRAM_CTRL_REG)
		printf "SDRAM_Wait_Idle-4\n"
		if ($temp_mem & 0x7) == 0
			printf "SDRAM_Wait_Idle-5\n"
			set $flag = 0x0
		else
			printf "SDRAM_Wait_Idle-6\n"
			set $flag = 0x1
		end
		printf "SDRAM_Wait_Idle-7\n"
	end	
end

#SDRAM_Set_DIMM_Map
define SDRAM_Set_DIMM_Map
	printf "SDRAM_Set_DIMM_Map-1\n"
	printf "argc=%d\n", $argc
	set $dimm1_en = $arg0
	set $dimm0_banks = $arg1
	set $dimm0_map = $arg2
	set $dimm1_banks = $arg3
	set $dimm1_map = $arg4
	printf "SDRAM_Set_DIMM_Map-2\n"

	set $dimm1_active 	= $dimm1_en
	set $dimm_banks	    = $dimm0_banks
	set $map_mode 		= $dimm0_map
	set $map1_mode		= $dimm1_map
	set $temp = 0
	printf "SDRAM_Set_DIMM_Map-3\n"
	set $temp = *((unsigned int*)$SDRAM_CTRL_REG)
	printf "SDRAM_Set_DIMM_Map-4\n"
	set *(unsigned int*)$SDRAM_CTRL_REG  = (($temp&0x0000ffff) | (($SDRAM_TurnAround_Mode<<31)|($SDRAM_OE_Post_En<<30) | ($SDRAM_OE_Pre_En<<29)))
	printf "SDRAM_Set_DIMM_Map-4-\n"
	set *(unsigned int*)$SDRAM_CTRL_REG =(($temp&0x0000ffff)|(($SDRAM_TurnAround_Mode<<31)|($SDRAM_OE_Post_En<<30)|($SDRAM_OE_Pre_En<<29)|($SDRAM_DQ_Mode<<28)|($dimm1_active<<27)|(0x0<<26)|($dimm1_banks<<25)|($dimm_banks<<24)|($map1_mode<<20)|($map_mode<<16)))
	printf "SDRAM_Set_DIMM_Map-5\n"
end

#SDRAM_Set_TimeParam
define SDRAM_Set_TimeParam
	set $temp = 0
	set $temp = *((unsigned int*)($SDRAM_CTRL_REG + 4))
	set *(unsigned int*)($SDRAM_CTRL_REG + 4) = (($temp&0xffff0000)|(($SDRAM_Ras_ActTime<<12)|($SDRAM_Ras_RefCyc<<8)|($SDRAM_CtoC_dly<<7)|($SDRAM_RtoR_dly<<6)|($SDRAM_RtoC_dly<<2)|($SDRAM_Ras_PreTime)))
end

#SDRAM_NOP
define SDRAM_NOP
	set $temp = 0
	SDRAM_Wait_Idle
	set $temp = *((unsigned int*)($SDRAM_CTRL_REG))
	set *(unsigned int*)($SDRAM_CTRL_REG) = (($temp&0xffffff00) | 0x0)
end


#SDRAM_PrechargeAll
define SDRAM_PrechargeAll
	set $temp = 0
	SDRAM_Wait_Idle
	set $temp = *((unsigned int*)($SDRAM_CTRL_REG))
	set *(unsigned int*)($SDRAM_CTRL_REG) = (($temp&0xffffff00) | 0x2)
end

#SDRAM_Mode_Set
define SDRAM_Mode_Set
	set $temp = 0
	SDRAM_Wait_Idle
	set $temp = *((unsigned int*)($SDRAM_CTRL_REG + 4))
	set *(unsigned int*)($SDRAM_CTRL_REG + 4) = (($temp&0xff00ffff) | (($SDRAM_Cas_Latency<<20)|($SDRAM_Interleave<<19)|($SDRAM_Burst_Length<<16)))
	set $temp = *((unsigned int*)($SDRAM_CTRL_REG))
	set *(unsigned int*)($SDRAM_CTRL_REG) = (($temp&0xffffff00) | 0x1)
end

#SDRAM_Refresh
define SDRAM_Refresh
	set $temp = 0
	SDRAM_Wait_Idle
	set $temp = *((unsigned int*)($SDRAM_CTRL_REG))
	set *(unsigned int*)($SDRAM_CTRL_REG) = (($temp&0xffffff00) | 0x3)
end

#SDRAM_Set_Refresh_Timer
define SDRAM_Set_Refresh_Timer
	printf "SDRAM_Set_Refresh_Timer-1\n"
	set $ref_init = $arg0
	printf "SDRAM_Set_Refresh_Timer-2\n"
	set $temp = 0
	printf "SDRAM_Set_Refresh_Timer-3\n"
	set $temp = *((unsigned int*)($SDRAM_CTRL_REG))
	printf "SDRAM_Set_Refresh_Timer-4\n"
	set *(unsigned int*)($SDRAM_CTRL_REG) = (($temp&0xffff00FF) | ($ref_init<<8))
	printf "SDRAM_Set_Refresh_Timer-5\n"
end

#SDRAM_Ref_Disable
define SDRAM_Ref_Disable
	printf "SDRAM_Ref_Disable-0\n"
	SDRAM_Wait_Idle
	printf "SDRAM_Ref_Disable-1\n"
	SDRAM_Set_Refresh_Timer 0x0
	printf "SDRAM_Ref_Disable-2\n"
	SDRAM_Wait_Idle
	printf "SDRAM_Ref_Disable-3\n"
end



#DIMM_Set_Map_Mode
define DIMM_Set_Map_Mode
	printf "DIMM_Set_Map_Mode-0\n"
	set $dimm0_banks = 0
    set $dimm0_map = 0
    set $dimm1_en = 0
    set $dimm1_banks = 0
    set $dimm1_map = 0
    set $sdram_row0_map = 0
    set $sdram_row1_base = 0
    set $sdram_row1_map = 0
    set $SDRAM_DIMM1_BASE = 0

	set $sdram_row0_map  = 0x6
	set $sdram_row1_base = 0x04000000
	printf "DIMM_Set_Map_Mode-1\n"
	
	if $SDRAM_DQ_Mode == 1
		printf "DIMM_Set_Map_Mode-2\n"
		set $SDRAM_DIMM1_BASE = 0x02000000
	else
		set $SDRAM_DIMM1_BASE = 0x04000000
		printf "DIMM_Set_Map_Mode-3\n"
	end
	printf "DIMM_Set_Map_Mode-4\n"
	
	set $dimm0_banks = 0x1
	printf "DIMM_Set_Map_Mode-5\n"
    #dimm0_map                     =       0x6
    set $dimm0_map = 0x5
	printf "DIMM_Set_Map_Mode-6\n"
	
	set $dimm1_en        = 0x0
    set $sdram_row1_map  = 0x0
    set $dimm1_banks     = 0x0
    set $dimm1_map       = 0x0
	printf "DIMM_Set_Map_Mode-7\n"
	
	
	SDRAM_Set_DIMM_Map $dimm1_en $dimm0_banks $dimm0_map $dimm1_banks $dimm1_map
	printf "DIMM_Set_Map_Mode-8\n"
end


define dram_pinmux_config
printf "pinmux configuration starts ... \n"
            set *(unsigned int*)(0x400002DC) |= 1<<24
            set *(unsigned int*)(0x40000324) |= 0xf<<16 
            set *(unsigned int*)(0x400002E8) |= 1<<10   
            set *(unsigned int*)(0x40000338) |= 0xf<<20 
            set *(unsigned int*)(0x400002E8) |= 1<<14  
            set *(unsigned int*)(0x40000338) |= 0xf<<28
            set *(unsigned int*)(0x400002E8) |= 1<<18 
            set *(unsigned int*)(0x4000033C) |= 0xf<<4 
            set *(unsigned int*)(0x400002E8) |= 1<<26  
            set *(unsigned int*)(0x4000033C) |= 0xf<<20
            set *(unsigned int*)(0x400002E8) |= 1<<30   
            set *(unsigned int*)(0x4000033C) |= 0xf<<28
            set *(unsigned int*)(0x400002EC) |= 1<<2    
            set *(unsigned int*)(0x40000340) |= 0xf<<4 
            set *(unsigned int*)(0x400002EC) |= 1<<6      
            set *(unsigned int*)(0x40000340) |= 0xf<<12
            set *(unsigned int*)(0x400002EC) |= 1<<10     
            set *(unsigned int*)(0x40000340) |= 0xf<<20
            set *(unsigned int*)(0x400002E4) |= 1<<10    
            set *(unsigned int*)(0x40000330) |= 0xf<<20
            set *(unsigned int*)(0x400002E4) |= 1<<14   
            set *(unsigned int*)(0x40000330) |= 0xf<<28
            set *(unsigned int*)(0x400002E4) |= 1<<18    
            set *(unsigned int*)(0x40000334) |= 0xf<<4 
            set *(unsigned int*)(0x400002E4) |= 1<<22     
            set *(unsigned int*)(0x40000334) |= 0xf<<12
            set *(unsigned int*)(0x400002E4) |= 1<<26  
            set *(unsigned int*)(0x40000334) |= 0xf<<20
            set *(unsigned int*)(0x400002E4) |= 1<<30   
            set *(unsigned int*)(0x40000334) |= 0xf<<28
            set *(unsigned int*)(0x400002E8) |= 1<<2     
            set *(unsigned int*)(0x40000338) |= 0xf<<4 
            set *(unsigned int*)(0x400002E8) |= 1<<6  
            set *(unsigned int*)(0x40000338) |= 0xf<<12
            set *(unsigned int*)(0x400002E4) |= 1<<28    
            set *(unsigned int*)(0x40000334) |= 0xf<<24
            set *(unsigned int*)(0x400002E8) |= 1<<0   
            set *(unsigned int*)(0x40000338) |= 0xf<<0 
            set *(unsigned int*)(0x400002E8) |= 1<<4     
            set *(unsigned int*)(0x40000338) |= 0xf<<8 
            set *(unsigned int*)(0x400002E8) |= 1<<8     
            set *(unsigned int*)(0x40000338) |= 0xf<<16
            set *(unsigned int*)(0x400002EC) |= 1<<8     
            set *(unsigned int*)(0x40000340) |= 0xf<<16
            set *(unsigned int*)(0x400002EC) |= 1<<12     
            set *(unsigned int*)(0x40000340) |= 0xf<<24
            set *(unsigned int*)(0x400002EC) |= 1<<14     
            set *(unsigned int*)(0x40000340) |= 0xf<<28
            set *(unsigned int*)(0x400002EC) |= 1<<16     
            set *(unsigned int*)(0x40000344) |= 0xf<<0 
            set *(unsigned int*)(0x400002C4) |= 1<<18     
            set *(unsigned int*)(0x400002F4) |= 0xf<<4 
            set *(unsigned int*)(0x400002C4) |= 1<<20     
            set *(unsigned int*)(0x400002F4) |= 0xf<<8 
            set *(unsigned int*)(0x400002D0) |= 1<<4     
            set *(unsigned int*)(0x40000308) |= 0xf<<8 
            set *(unsigned int*)(0x400002D0) |= 1<<8      
            set *(unsigned int*)(0x40000308) |= 0xf<<16
            set *(unsigned int*)(0x400002D0) |= 1<<12     
            set *(unsigned int*)(0x40000308) |= 0xf<<24
            set *(unsigned int*)(0x400002D0) |= 1<<16    
            set *(unsigned int*)(0x4000030C) |= 0xf<<0 
            set *(unsigned int*)(0x400002D0) |= 1<<24    
            set *(unsigned int*)(0x4000030C) |= 0xf<<16
            set *(unsigned int*)(0x400002D0) |= 1<<28    
            set *(unsigned int*)(0x4000030C) |= 0xf<<24
            set *(unsigned int*)(0x400002D0) |= 1<<14    
            set *(unsigned int*)(0x40000308) |= 0xf<<28
            set *(unsigned int*)(0x400002D0) |= 1<<18    
            set *(unsigned int*)(0x4000030C) |= 0xf<<4 
            set *(unsigned int*)(0x400002D0) |= 1<<22    
            set *(unsigned int*)(0x4000030C) |= 0xf<<12
            set *(unsigned int*)(0x400002D0) |= 1<<26    
            set *(unsigned int*)(0x4000030C) |= 0xf<<20
            set *(unsigned int*)(0x400002D0) |= 1<<30    
            set *(unsigned int*)(0x4000030C) |= 0xf<<28
            set *(unsigned int*)(0x400002D4) |= 1<<4    
            set *(unsigned int*)(0x40000310) |= 0xf<<8 
            set *(unsigned int*)(0x400002D4) |= 1<<8     
            set *(unsigned int*)(0x40000310) |= 0xf<<16
            set *(unsigned int*)(0x400002D4) |= 1<<12      
            set *(unsigned int*)(0x40000310) |= 0xf<<24
            set *(unsigned int*)(0x400002D4) |= 1<<16    
            set *(unsigned int*)(0x40000314) |= 0xf<<0 
            set *(unsigned int*)(0x400002D4) |= 1<<18   
            set *(unsigned int*)(0x40000314) |= 0xf<<4 
            set *(unsigned int*)(0x400002D0) |= 1<<10   
            set *(unsigned int*)(0x40000308) |= 0xf<<20
            set *(unsigned int*)(0x400002D4) |= 1<<22    
            set *(unsigned int*)(0x40000314) |= 0xf<<12
            set *(unsigned int*)(0x400002D4) |= 1<<0    
            set *(unsigned int*)(0x40000310) |= 0xf<<0 
            set *(unsigned int*)(0x400002CC) |= 1<<18    
            set *(unsigned int*)(0x40000304) |= 0xf<<4 
            set *(unsigned int*)(0x400002CC) |= 1<<30   
            set *(unsigned int*)(0x40000304) |= 0xf<<28
            set *(unsigned int*)(0x400002CC) |= 1<<4    
            set *(unsigned int*)(0x40000300) |= 0xf<<8 
            set *(unsigned int*)(0x400002D4) |= 1<<26  
            set *(unsigned int*)(0x40000314) |= 0xf<<20
            set *(unsigned int*)(0x400002CC) |= 1<<6   
            set *(unsigned int*)(0x40000300) |= 0xf<<12
            set *(unsigned int*)(0x400002CC) |= 1<<26   
            set *(unsigned int*)(0x40000304) |= 0xf<<20
            set *(unsigned int*)(0x400002CC) |= 1<<14  
            set *(unsigned int*)(0x40000300) |= 0xf<<28
            set *(unsigned int*)(0x400002D4) |= 1<<30  
            set *(unsigned int*)(0x40000314) |= 0xf<<28
            set *(unsigned int*)(0x400002CC) |= 1<<10   
            set *(unsigned int*)(0x40000300) |= 0xf<<20
            set *(unsigned int*)(0x400002CC) |= 1<<12   
            set *(unsigned int*)(0x40000300) |= 0xf<<24
            set *(unsigned int*)(0x400002CC) |= 1<<22  
            set *(unsigned int*)(0x40000304) |= 0xf<<12
            set *(unsigned int*)(0x400002D0) |= 1<<2    
            set *(unsigned int*)(0x40000308) |= 0xf<<4
            set *(unsigned int*)(0x400002D0) |= 1<<6     
            set *(unsigned int*)(0x40000308) |= 0xf<<12
			
			set *(unsigned int*)(0x40000298) |= (0xf<<0)|(0xf<<4)|(0xf<<8)|(0xf<<12)|(0xf<<16)|(0xf<<20)|(0xf<<24)|(0xf<<28)
			set *(unsigned int*)(0x4000029c) |= (0xf<<0)|(0xf<<4)|(0xf<<8)|(0xf<<12)|(0xf<<16)|(0xf<<20)|(0xf<<24)|(0xf<<28)
			set *(unsigned int*)(0x400002a0) |= (0xf<<0)|(0xf<<4)|(0xf<<8)|(0xf<<12)|(0xf<<16)|(0xf<<20)|(0xf<<24)|(0xf<<28)
			set *(unsigned int*)(0x400002a4) |= (0xf<<0)|(0xf<<4)|(0xf<<8)|(0xf<<12)|(0xf<<16)|(0xf<<20)|(0xf<<24)|(0xf<<28)
			set *(unsigned int*)(0x400002a8) |= (0xf<<0)|(0xf<<4)|(0xf<<8)|(0xf<<12)|(0xf<<16)|(0xf<<20)|(0xf<<24)|(0xf<<28)
			set *(unsigned int*)(0x400002ac) |= (0xf<<0)|(0xf<<4)|(0xf<<8)|(0xf<<12)|(0xf<<16)|(0xf<<20)|(0xf<<24)|(0xf<<28)
			set *(unsigned int*)(0x400002b0) |= (0xf<<0)|(0xf<<4)|(0xf<<8)|(0xf<<12)|(0xf<<16)|(0xf<<20)|(0xf<<24)|(0xf<<28)
			set *(unsigned int*)(0x400002b4) |= (0xf<<0)|(0xf<<4)|(0xf<<8)|(0xf<<12)|(0xf<<16)|(0xf<<20)|(0xf<<24)|(0xf<<28)
			set *(unsigned int*)(0x400002b8) |= (0xf<<0)|(0xf<<4)|(0xf<<8)|(0xf<<12)|(0xf<<16)|(0xf<<20)|(0xf<<24)|(0xf<<28)
			set *(unsigned int*)(0x400002bc) |= (0xf<<0)|(0xf<<4)|(0xf<<8)|(0xf<<12)|(0xf<<16)|(0xf<<20)|(0xf<<24)|(0xf<<28)
			set *(unsigned int*)(0x400002c0) |= (0xf<<0)|(0xf<<4)|(0xf<<8)|(0xf<<12)|(0xf<<16)|(0xf<<20)|(0xf<<24)|(0xf<<28)
printf "pinmux configuration ends ... \n"
end

define dram_init
  printf "0\n"
  set $referenceCount = 0
  printf "1\n"
	if $referenceCount == 0
		printf "2\n"
		set *(unsigned int*)(0x40000070) = (1<<7)
		printf "2-\n"
		set *(unsigned int*)(0x40000080) = (1<<7)
		printf "2--\n"
		SDRAM_Ref_Disable
		printf "3\n"
		debug_sdram
		printf "4\n"
		DIMM_Set_Map_Mode
		printf "5\n"
		debug_sdram
		printf "6\n"
		SDRAM_Set_TimeParam
		printf "7\n"
		debug_sdram
		printf "8\n"
		SDRAM_NOP
		SDRAM_NOP
		SDRAM_NOP
		printf "9\n"
		SDRAM_PrechargeAll
		printf "10\n"
		debug_sdram
		SDRAM_Mode_Set
		printf "11\n"
		debug_sdram
		SDRAM_Set_Refresh_Timer 0x05
		printf "12\n"
		debug_sdram
		SDRAM_Refresh
		SDRAM_Refresh
		SDRAM_Refresh
		SDRAM_Refresh
		SDRAM_Refresh
		SDRAM_Refresh
		SDRAM_Refresh
		SDRAM_Refresh
		debug_sdram
		SDRAM_Wait_Idle
		printf "13\n"
		debug_sdram
		set $referenceCount = 1
	end
	set *(unsigned int*)(0x40039290) |= (0xA)<<12
end



define kdp_new_body
    set $src = (unsigned int)CMD_BASE_BODY
	restore Z:\\\New_Performance\\bodyimpyolo\\generated_cmd_hex.out.bin binary $src
	set $src = (unsigned int)WEI_BASE_BODY
	restore Z:\\\New_Performance\\bodyimpyolo\\full_weights.bin binary $src
	set $src = (unsigned int)RecvBufferBody
	restore Z:\\\New_Performance\\bodyimpyolo\\input_fpga.out.bin binary $src
	printf "load finished"	
end

document kdp_new_body
Load cmd weight and base for Gesture
Usage: usage
Exapmple:
	kdp_new_body
end
